/**
 * Backtesting engine — CoinGecko daily prices (365 days).
 * Each strategy has unique signal logic with different trade timing.
 * More signals generated by relaxing thresholds.
 */

const STRATEGY_TO_CG: Record<number, string> = {
  1: 'bitcoin',  2: 'ethereum', 3: 'bitcoin',  4: 'bitcoin',
  5: 'bitcoin',  6: 'solana',   7: 'ethereum', 8: 'chainlink',
  9: 'ethereum', 10: 'ethereum', 11: 'bitcoin', 12: 'bitcoin',
};

// ── Indicators ────────────────────────────────────────────────────────────────

function ema(p: number[], period: number, idx: number): number {
  const k = 2 / (period + 1);
  let e = p[0];
  for (let i = 1; i <= idx; i++) e = p[i] * k + e * (1 - k);
  return e;
}

function rsi(p: number[], period: number, idx: number): number {
  if (idx < period) return 50;
  let g = 0, l = 0;
  for (let i = idx - period + 1; i <= idx; i++) {
    const d = p[i] - p[i - 1];
    if (d > 0) g += d; else l -= d;
  }
  return l === 0 ? 100 : 100 - 100 / (1 + g / l);
}

function sma(p: number[], period: number, idx: number): number {
  const s = p.slice(Math.max(0, idx - period + 1), idx + 1);
  return s.reduce((a, b) => a + b, 0) / s.length;
}

function stddev(p: number[], period: number, idx: number): number {
  const s = p.slice(Math.max(0, idx - period + 1), idx + 1);
  const m = s.reduce((a, b) => a + b, 0) / s.length;
  return Math.sqrt(s.reduce((a, b) => a + (b - m) ** 2, 0) / s.length);
}

// ── Signal functions — each strategy has unique timing ────────────────────────

// Strategy 1: Breakout — 10-day high/low breakout with RSI
function sigBreakout(p: number[], i: number): 'buy' | 'sell' | null {
  if (i < 12) return null;
  const h10 = Math.max(...p.slice(i - 10, i));
  const l10 = Math.min(...p.slice(i - 10, i));
  const r = rsi(p, 10, i);
  const e20 = ema(p, 20, i);
  if (p[i] > h10 * 0.998 && r > 50 && p[i] > e20) return 'buy';
  if (p[i] < l10 * 1.002 && r < 50 && p[i] < e20) return 'sell';
  return null;
}

// Strategy 2: RSI mean reversion — crosses 35/65 with EMA
function sigRSI(p: number[], i: number): 'buy' | 'sell' | null {
  if (i < 15) return null;
  const r = rsi(p, 12, i), pr = rsi(p, 12, i - 1);
  const e20 = ema(p, 20, i);
  if (pr < 35 && r >= 35 && p[i] > e20 * 0.995) return 'buy';
  if (pr > 65 && r <= 65 && p[i] < e20 * 1.005) return 'sell';
  return null;
}

// Strategy 3: EMA5/EMA13 crossover (fast)
function sigVWAP(p: number[], i: number): 'buy' | 'sell' | null {
  if (i < 15) return null;
  const e5 = ema(p, 5, i), pe5 = ema(p, 5, i - 1);
  const e13 = ema(p, 13, i), pe13 = ema(p, 13, i - 1);
  const r = rsi(p, 10, i);
  if (pe5 < pe13 && e5 >= e13 && r > 45) return 'buy';
  if (pe5 > pe13 && e5 <= e13 && r < 55) return 'sell';
  return null;
}

// Strategy 4: EMA bounce — price crosses EMA21 with trend
function sigSR(p: number[], i: number): 'buy' | 'sell' | null {
  if (i < 25) return null;
  const e21 = ema(p, 21, i), pe21 = ema(p, 21, i - 1);
  const e50 = ema(p, 50, i);
  const r = rsi(p, 14, i);
  if (p[i - 1] < pe21 && p[i] >= e21 && p[i] > e50 * 0.99 && r > 42) return 'buy';
  if (p[i - 1] > pe21 && p[i] <= e21 && p[i] < e50 * 1.01 && r < 58) return 'sell';
  return null;
}

// Strategy 5: EMA13/EMA34 golden/death cross
function sigEMA(p: number[], i: number): 'buy' | 'sell' | null {
  if (i < 40) return null;
  const e13 = ema(p, 13, i), e34 = ema(p, 34, i);
  const pe13 = ema(p, 13, i - 1), pe34 = ema(p, 34, i - 1);
  const r = rsi(p, 14, i);
  if (pe13 < pe34 && e13 >= e34 && r > 48) return 'buy';
  if (pe13 > pe34 && e13 <= e34 && r < 52) return 'sell';
  return null;
}

// Strategy 6: Bollinger Band — touch + RSI confirmation
function sigBollinger(p: number[], i: number): 'buy' | 'sell' | null {
  if (i < 22) return null;
  const mid = sma(p, 20, i), sd = stddev(p, 20, i);
  const upper = mid + 1.8 * sd, lower = mid - 1.8 * sd;
  const r = rsi(p, 14, i);
  if (p[i] <= lower * 1.005 && r < 38 && p[i] >= p[i - 1]) return 'buy';
  if (p[i] >= upper * 0.995 && r > 62 && p[i] <= p[i - 1]) return 'sell';
  return null;
}

// Strategy 7: SR flip — 2-bar EMA confirmation
function sigSR7(p: number[], i: number): 'buy' | 'sell' | null {
  if (i < 20) return null;
  const e13 = ema(p, 13, i), pe13 = ema(p, 13, i - 1);
  const e34 = ema(p, 34, i);
  const r = rsi(p, 14, i);
  if (p[i - 1] >= pe13 && p[i] >= e13 && p[i] > e34 && r > 46) return 'buy';
  if (p[i - 1] <= pe13 && p[i] <= e13 && p[i] < e34 && r < 54) return 'sell';
  return null;
}

// Strategy 8: MACD zero-line cross
function sigMACD(p: number[], i: number): 'buy' | 'sell' | null {
  if (i < 28) return null;
  const macd  = ema(p, 12, i)     - ema(p, 26, i);
  const pmacd = ema(p, 12, i - 1) - ema(p, 26, i - 1);
  const e34 = ema(p, 34, i);
  const r = rsi(p, 14, i);
  if (pmacd < 0 && macd >= 0 && r > 46) return 'buy';
  if (pmacd > 0 && macd <= 0 && r < 54) return 'sell';
  return null;
}

// Strategy 9: Fibonacci 61.8/38.2 retracement
function sigFib(p: number[], i: number): 'buy' | 'sell' | null {
  if (i < 30) return null;
  const h = Math.max(...p.slice(i - 30, i));
  const l = Math.min(...p.slice(i - 30, i));
  const range = h - l;
  if (range === 0) return null;
  const f618 = h - range * 0.618;
  const f382 = h - range * 0.382;
  const r = rsi(p, 14, i);
  if (Math.abs(p[i] - f618) / f618 < 0.02 && r < 45 && p[i] >= p[i - 1]) return 'buy';
  if (Math.abs(p[i] - f382) / f382 < 0.02 && r > 55 && p[i] <= p[i - 1]) return 'sell';
  return null;
}

// Strategy 10: ML consensus — 4-indicator vote
function sigML(p: number[], i: number): 'buy' | 'sell' | null {
  if (i < 40) return null;
  const r = rsi(p, 14, i);
  const e13 = ema(p, 13, i), e34 = ema(p, 34, i);
  const macd  = ema(p, 12, i)     - ema(p, 26, i);
  const pmacd = ema(p, 12, i - 1) - ema(p, 26, i - 1);
  let bull = 0, bear = 0;
  if (r > 50) bull++; else bear++;
  if (p[i] > e13) bull++; else bear++;
  if (e13 > e34) bull++; else bear++;
  if (macd > pmacd) bull++; else bear++;
  if (bull >= 3 && p[i] >= p[i - 1]) return 'buy';
  if (bear >= 3 && p[i] <= p[i - 1]) return 'sell';
  return null;
}

// Strategy 11: Opening range breakout — 5-day high/low
function sigORB(p: number[], i: number): 'buy' | 'sell' | null {
  if (i < 8) return null;
  const h5 = Math.max(...p.slice(i - 5, i));
  const l5 = Math.min(...p.slice(i - 5, i));
  const e20 = ema(p, 20, i);
  const r = rsi(p, 10, i);
  if (p[i] > h5 * 0.999 && p[i] > e20 && r > 50) return 'buy';
  if (p[i] < l5 * 1.001 && p[i] < e20 && r < 50) return 'sell';
  return null;
}

// Strategy 12: Turtle — 20-day breakout (best strategy, most signals)
function sigTurtle(p: number[], i: number): 'buy' | 'sell' | null {
  if (i < 22) return null;
  const h20 = Math.max(...p.slice(i - 20, i));
  const l20 = Math.min(...p.slice(i - 20, i));
  const e50 = ema(p, 50, i);
  const r = rsi(p, 14, i);
  if (p[i] > h20 * 0.997 && p[i] > e50 * 0.99 && r > 50) return 'buy';
  if (p[i] < l20 * 1.003 && p[i] < e50 * 1.01 && r < 50) return 'sell';
  return null;
}

const SIGNAL_FN: Record<number, (p: number[], i: number) => 'buy' | 'sell' | null> = {
  1: sigBreakout, 2: sigRSI,  3: sigVWAP,
  4: sigSR,       5: sigEMA,  6: sigBollinger,
  7: sigSR7,      8: sigMACD, 9: sigFib,
  10: sigML,      11: sigORB, 12: sigTurtle,
};

// ── Types ─────────────────────────────────────────────────────────────────────

export interface BacktestPoint {
  date: string;
  price: number;
  equity: number;
  signal: 'buy' | 'sell' | null;
}

export interface BacktestStats {
  totalTrades: number;
  winRate: number;
  avgWin: number;
  avgLoss: number;
  totalReturn: number;
  maxDrawdown: number;
}

// ── Main ──────────────────────────────────────────────────────────────────────

export async function runBacktest(
  strategyId: number,
  market: string
): Promise<{ points: BacktestPoint[]; stats: BacktestStats }> {
  const cgId = STRATEGY_TO_CG[strategyId] || 'bitcoin';
  const empty = { points: [], stats: { totalTrades: 0, winRate: 0, avgWin: 0, avgLoss: 0, totalReturn: 0, maxDrawdown: 0 } };

  let prices: number[] = [];
  let dates: string[] = [];

  try {
    // Daily data for 365 days — one year of history
    const res = await fetch(
      `https://api.coingecko.com/api/v3/coins/${cgId}/market_chart?vs_currency=usd&days=365&interval=daily`
    );
    const data = await res.json();
    const raw: [number, number][] = data.prices || [];
    prices = raw.map(([, p]) => p);
    dates  = raw.map(([t]) => {
      const d = new Date(t);
      return `${d.toLocaleString('default', { month: 'short' })} ${d.getDate()}`;
    });
  } catch { return empty; }

  if (prices.length < 30) return empty;

  const fn = SIGNAL_FN[strategyId] || sigBreakout;
  const points: BacktestPoint[] = [];

  // ── Simulate trades with alternating buy/sell enforcement ─────────────────
  let equity = 10000;
  let inTrade = false;
  let entryPrice = 0;
  let entryEquity = 0;
  let lastSignal: 'buy' | 'sell' | null = null;
  const trades: { pnl: number }[] = [];
  let peakEquity = 10000;
  let maxDD = 0;

  // Minimum hold period per strategy (days) — creates different timing
  const minHoldMap: Record<number, number> = {
    1: 3, 2: 4, 3: 2, 4: 5, 5: 7, 6: 3,
    7: 4, 8: 5, 9: 6, 10: 4, 11: 2, 12: 8,
  };
  const minHold = minHoldMap[strategyId] || 3;
  let holdCount = 0;

  for (let i = 0; i < prices.length; i++) {
    const rawSignal = fn(prices, i);
    let chartSignal: 'buy' | 'sell' | null = null;

    if (inTrade) {
      holdCount++;
      const pnl = (prices[i] - entryPrice) / entryPrice;
      // Exit conditions: sell signal after min hold, or stop loss, or take profit
      const canExit = holdCount >= minHold;
      const hitStop   = pnl <= -0.05;
      const hitTarget = pnl >= 0.12;
      const sellSig   = rawSignal === 'sell' && canExit;

      if (hitStop || hitTarget || sellSig) {
        equity = entryEquity * (1 + pnl * 0.95);
        trades.push({ pnl: pnl * 100 });
        inTrade = false;
        chartSignal = 'sell';
        lastSignal = 'sell';
        holdCount = 0;
      }
    } else {
      if (rawSignal === 'buy' && lastSignal !== 'buy') {
        inTrade = true;
        entryPrice = prices[i];
        entryEquity = equity;
        holdCount = 0;
        chartSignal = 'buy';
        lastSignal = 'buy';
      }
    }

    // Current equity (unrealized if in trade)
    let currentEquity = equity;
    if (inTrade) {
      const unrealized = (prices[i] - entryPrice) / entryPrice;
      currentEquity = entryEquity * (1 + unrealized * 0.95);
    }

    if (currentEquity > peakEquity) peakEquity = currentEquity;
    const dd = (peakEquity - currentEquity) / peakEquity * 100;
    if (dd > maxDD) maxDD = dd;

    // Push every point (daily data is already manageable ~365 pts)
    points.push({
      date: dates[i],
      price: Math.round(prices[i] * 100) / 100,
      equity: Math.round(currentEquity),
      signal: chartSignal,
    });
  }

  // Close open trade at end
  if (inTrade && prices.length > 0) {
    const pnl = (prices[prices.length - 1] - entryPrice) / entryPrice;
    const finalEq = entryEquity * (1 + pnl * 0.95);
    trades.push({ pnl: pnl * 100 });
    if (points.length > 0) {
      points[points.length - 1] = {
        ...points[points.length - 1],
        equity: Math.round(finalEq),
        signal: 'sell',
      };
    }
  }

  const wins   = trades.filter(t => t.pnl > 0);
  const losses = trades.filter(t => t.pnl <= 0);
  const finalEquity = points[points.length - 1]?.equity ?? 10000;

  return {
    points,
    stats: {
      totalTrades: trades.length,
      winRate:     trades.length > 0 ? Math.round((wins.length / trades.length) * 100) : 0,
      avgWin:      wins.length   > 0 ? parseFloat((wins.reduce((a, t) => a + t.pnl, 0) / wins.length).toFixed(1)) : 0,
      avgLoss:     losses.length > 0 ? parseFloat((Math.abs(losses.reduce((a, t) => a + t.pnl, 0) / losses.length)).toFixed(1)) : 0,
      totalReturn: parseFloat(((finalEquity - 10000) / 10000 * 100).toFixed(1)),
      maxDrawdown: parseFloat(maxDD.toFixed(1)),
    },
  };
}
